### PR TITLE
hotfix/RLP-692/onboarding-wrong-http-status

### PR DESCRIPTION
**Pull request by JONAF2103**
RLP-692: This fixes the on-boarding from LC, basically we wasn't registering the LC into Matrix because of this error.

Explanation:

The last call before that check is **register_light_client** located in python.py:1633 at the moment. That method has a json as the result of the call, that json has fixed result_code values which are at the moment 200, 500, 403 and 409, reviewing the code you can see that those are the only values that the method result can have on the result_code param.

        address = to_checksum_address(address)

        light_client = self.raiden.wal.storage.get_light_client(address)

        pubhex = self.raiden.config["pubkey"].hex()
        encrypt_signed_password = encrypt(pubhex, signed_password.encode())
        encrypt_signed_display_name = encrypt(pubhex, signed_display_name.encode())
        encrypt_signed_seed_retry = encrypt(pubhex, signed_seed_retry.encode())

        if light_client is None:

            api_key = hexlify(os.urandom(20))
            api_key = api_key.decode("utf-8")
            #Check for limit light client
            if HUB_MAX_LIGHT_CLIENTS > len(self.get_all_light_clients()):
                result = self.raiden.wal.storage.save_light_client(
                    api_key=api_key,
                    address=address,
                    encrypt_signed_password=encrypt_signed_password.hex(),
                    encrypt_signed_display_name=encrypt_signed_display_name.hex(),
                    encrypt_signed_seed_retry=encrypt_signed_seed_retry.hex(),
                    current_server_name=server_name,
                    pending_for_deletion=0
                )

                if result > 0:
                    result = {"address": address,
                              "encrypt_signed_password": encrypt_signed_password.hex(),
                              "encrypt_signed_display_name": encrypt_signed_display_name.hex(),
                              "api_key": api_key,
                              "encrypt_signed_seed_retry": encrypt_signed_seed_retry.hex(),
                              "message": "successfully registered",
                              "result_code": 200}
                else:
                    result = {"message": "An unexpected error has occurred.",
                              "result_code": 500}
            else:
                result = {"message": "Limit of registered light clients reached.",
                          "result_code": 403}
        else:
            result = {"address": address,
                      "encrypt_signed_password": encrypt_signed_password.hex(),
                      "encrypt_signed_display_name": encrypt_signed_display_name.hex(),
                      "api_key": light_client["api_key"],
                      "encrypt_signed_seed_retry": encrypt_signed_seed_retry.hex(),
                      "message": "Already registered",
                      "result_code": 409}

        return result

There we have the actual body of **register_light_client** so we can review it and see why 200 make sense instead of 0. This was probably a change of codes and for some reason we never updated the 0 value with the 200 in the call.

### CODE REVIEW

**Comment by rorolopetegui** [comment]
Can you explain why 200 makes this works as expected? 
So in the near future if someone sees this 200, we can understand why that is in there.

**Review by rorolopetegui — CHANGES_REQUESTED** [review]
Can you explain why 200 makes this works as expected?
So in the near future if someone sees this 200, we can understand why that is in there.

**Comment by JONAF2103** [comment]
> Can you explain why 200 makes this works as expected?
> So in the near future if someone sees this 200, we can understand why that is in there.

Yes, because the last call before that check is **register_light_client** located in python.py:1633 at the moment. That method has a json as the result of the call, that json has fixed result_code values which are at the moment 200, 500, 403 and 409, reviewing the code you can see that those are the only values that the method result can have on the result_code param.




        address = to_checksum_address(address)

        light_client = self.raiden.wal.storage.get_light_client(address)

        pubhex = self.raiden.config["pubkey"].hex()
        encrypt_signed_password = encrypt(pubhex, signed_password.encode())
        encrypt_signed_display_name = encrypt(pubhex, signed_display_name.encode())
        encrypt_signed_seed_retry = encrypt(pubhex, signed_seed_retry.encode())

        if light_client is None:

            api_key = hexlify(os.urandom(20))
            api_key = api_key.decode("utf-8")
            #Check for limit light client
            if HUB_MAX_LIGHT_CLIENTS > len(self.get_all_light_clients()):
                result = self.raiden.wal.storage.save_light_client(
                    api_key=api_key,
                    address=address,
                    encrypt_signed_password=encrypt_signed_password.hex(),
                    encrypt_signed_display_name=encrypt_signed_display_name.hex(),
                    encrypt_signed_seed_retry=encrypt_signed_seed_retry.hex(),
                    current_server_name=server_name,
                    pending_for_deletion=0
                )

                if result > 0:
                    result = {"address": address,
                              "encrypt_signed_password": encrypt_signed_password.hex(),
                              "encrypt_signed_display_name": encrypt_signed_display_name.hex(),
                              "api_key": api_key,
                              "encrypt_signed_seed_retry": encrypt_signed_seed_retry.hex(),
                              "message": "successfully registered",
                              "result_code": 200}
                else:
                    result = {"message": "An unexpected error has occurred.",
                              "result_code": 500}
            else:
                result = {"message": "Limit of registered light clients reached.",
                          "result_code": 403}
        else:
            result = {"address": address,
                      "encrypt_signed_password": encrypt_signed_password.hex(),
                      "encrypt_signed_display_name": encrypt_signed_display_name.hex(),
                      "api_key": light_client["api_key"],
                      "encrypt_signed_seed_retry": encrypt_signed_seed_retry.hex(),
                      "message": "Already registered",
                      "result_code": 409}

        return result



There you have the actual body of **register_light_client** so you can review it and see why 200 make sense instead of 0. This was probably a change of codes and for some reason we never updated the 0 value with the 200 in the call.

**Review by marcosmartinez7 — APPROVED** [review]
lgtm

**Review by rorolopetegui — APPROVED** [review]
lgtm

**Pull request merged**
