### PR TITLE
Rlp 656/action channel close signed tx

### PR DESCRIPTION
**Pull request by rorolopetegui**
Assigned default value for signed_tx in ActionChannelClose, when it is a non-lightclient doesnt need this attr

### CODE REVIEW

**Comment by marcosmartinez7** [comment]
We should remove all the test cases that are modified on this PR and are not related to the issue.

**Review by marcosmartinez7 — CHANGES_REQUESTED** [review]
Remove the test cases files that are not related to this PR.

**Comment by rorolopetegui** [comment]
This PR will be closed, cause git is not showing correctly the changes made by this.
I'll create a new PR

**Comment by rorolopetegui** [comment]
[Link to new PR](https://github.com/rsksmart/lumino/pull/83)

**Pull request closed without merging**
